### ISSUE TITLE
Example on how to secure an action using claims?

### ISSUE THREAD

**Issue by donnyv** [DmitrySikorsky/AspNetCoreCustomUserManager#1]
When using the default implementation in Asp.net core. You can secure a controller or one of the actions using an attribute. `[Authorize(Policy = "SubmitterOnly")]`

Can I still do that with this?

Also are the claims stored in the cookie for that user? Is there a way to look up what claims a user has instead?

Thanks

**Comment by DmitrySikorsky** [comment]
Hi! Thank you for your question. Yes, sure, you still can use that. This is an implementation I used in my Platformus project:

https://github.com/Platformus/Platformus/blob/master/src/Platformus.Security/Actions/AddAuthorizationAction.cs#L28

The main point is to collect auth policies from all the extensions. I do that using my IAuthorizationPolicyProvider interface.

Here is one of the implementations:

https://github.com/Platformus/Platformus/blob/master/src/Platformus.Domain/PolicyProviders/HasBrowseClassesPermissionAuthorizationPolicyProvider.cs#L9

Please, ask if you have any questions.

**Comment by donnyv** [comment]
Thanks for the help. I got it working! This project is exactly what I was looking for. The default implementation Microsoft uses is way over complicated.

**Comment by DmitrySikorsky** [comment]
Good! So, I close this issue for now.
