### ISSUE TITLE
extending to allow Admin to manage, roles, permissions and claims

### ISSUE THREAD

**Issue by ridingmower** [DmitrySikorsky/AspNetCoreCustomUserManager#3]
Hello, is there a view/sample page to manage the roles, permissions and claims. I like the simplicity, its better than the default. But a view for admin user to manage would be nice, and import users from excel.

**Comment by DmitrySikorsky** [comment]
Hi! No, this is only a user manager itself, without any UI, because the main purpose is to keep it simple and do not provide unnecessary features.
